### ISSUE TITLE
SubTitle() function issue

### ISSUE THREAD

**Issue by beshad** [markguinn/silverstripe-wishlist#4]
hi, I have problem when building this module and it appears to be the public function SubTitle() in code/WishListItem.php. the module works fine when i take away this function. the product does not have a subtitle why the need to the method? is this a bug? thanks

**Comment by tylerkidd** [comment]
@beshad which version of SilverShop are you using? ProductVariation's have the SubTitle method.

https://github.com/silvershop/silvershop-core/blob/master/code/product/variations/ProductVariation.php

**Comment by beshad** [comment]
@tylerkidd thanks for the quick reply. i use 2.2.1 (it says dev.master in composer). strangely it seems to be working now but it used to break the code every time i added a product to wish-list and navigated to wish-list page. was getting an error re SubTitle method hence i removed the function from code. i put it back past night and dev/build and to my surprise it works now! must have been some of updates i have done since start of the project, anyways thanks for the help. i am going to go ahead and close this issue, i will reopen if problem comes bak. cheers
